export const POPUUP_TYPES = [
  {id: 1, name: '패션/뷰티', selected: false},
  {id: 2, name: '캐릭터', selected: false},
  {id: 3, name: '식품/음료', selected: false},
  {id: 4, name: '웹툰/애니메이션', selected: false},
  {id: 5, name: '인테리어/소품', selected: false},
  {id: 6, name: '영화/드라마/예능', selected: false},
  {id: 7, name: '뮤지컬/연극', selected: false},
  {id: 8, name: '스포츠', selected: false},
  {id: 9, name: '게임', selected: false},
  {id: 10, name: 'IT/테크', selected: false},
  {id: 11, name: 'K-POP', selected: false},
  {id: 12, name: '주류', selected: false},
  {id: 13, name: '동물/식물', selected: false},
  {id: 14, name: '기타', selected: false},
  {id: 15, name: '🛍️마켓형', selected: false},
  {id: 16, name: '🖼️전시형', selected: false},
  {id: 17, name: '🏃체험형', selected: false},
];
