export const POPUUP_TYPES = [
  {id: 'fashionBeauty', name: '패션/뷰티', selected: false},
  {id: 'characters', name: '캐릭터', selected: false},
  {id: 'foodBeverage', name: '식품/음료', selected: false},
  {id: 'webtoonAni', name: '웹툰/애니메이션', selected: false},
  {id: 'interiorThings', name: '인테리어/소품', selected: false},
  {id: 'movie', name: '영화/드라마/예능', selected: false},
  {id: 'musical', name: '뮤지컬/연극', selected: false},
  {id: 'sports', name: '스포츠', selected: false},
  {id: 'game', name: '게임', selected: false},
  {id: 'itTech', name: 'IT/테크', selected: false},
  {id: 'kpop', name: 'K-POP', selected: false},
  {id: 'alcchol', name: '주류', selected: false},
  {id: 'animalPlant', name: '동물/식물', selected: false},
  // {id: '14', name: '기타', selected: false},
  {id: 'market', name: '🛍️마켓형', selected: false},
  {id: 'display', name: '🖼️전시형', selected: false},
  {id: 'experience', name: '🏃체험형', selected: false},
];
