export type AppNavigatorParamList = {
  Report: undefined;
  PopUpEditRequest: undefined;
  Entry: undefined;
  BasicLogin: undefined;
  PasswordReset: undefined;
  PrivacyPolicy: undefined;
  ServicePolicy: undefined;
  SignUpPreferenceSetting: undefined;
  SignUpNickNameSocial: undefined;
  SignUpEmail: undefined;
  SignUpAuthCode: undefined;
  SignUpNickName: undefined;
  SignUpSucceed: undefined;
  MainTabNavigator: undefined;
  ProfileEdit: undefined;
  PasswordChange: undefined;
  FAQ: undefined;
  KeywordAlarm: undefined;
  UserRegister: undefined;
  Policy: undefined;
  ReviewWrite: undefined;
  OperatorRegister: undefined;
  MemberDelete: undefined;
  PreferenceSetting: undefined;
  PopUpDetail: {id: number};
  Alarm: undefined;
  AlarmSetting: undefined;
  NoticeDetail: {nid: number};
  findInputScreen: undefined;
};
// Path: src/types/RootStackParamList.ts
