$RNFirebaseAsStaticFramework = true
$RNFirebaseAnalyticsWithoutAdIdSupport = true
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip
# #SETTING react-native-permissions
require_relative '../node_modules/react-native-permissions/scripts/setup'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

# #SETTING react-native-permissions
# prepare_react_native_project!
# ⬇️ uncomment wanted permissions
setup_permissions([
'AppTrackingTransparency',
# 'Bluetooth',
# 'Calendars',
# 'CalendarsWriteOnly',
# 'Camera',
# 'Contacts',
# 'FaceID',
# 'LocationAccuracy',
# 'LocationAlways',
# 'LocationWhenInUse',
# 'MediaLibrary',
# 'Microphone',
# 'Motion',
'Notifications',
# 'PhotoLibrary',
# 'PhotoLibraryAddOnly',
# 'Reminders',
# 'Siri',
# 'SpeechRecognition',
# 'StoreKit',
])

target 'PoppinProject' do

  config = use_native_modules!

  # #SETTING (도형) use_frameworks 삭제후 아래 기입, @reference https://www.inflearn.com/community/questions/572942/push-적용중-에러
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true

  # DateTimePicker SETTING
  pod 'RNDateTimePicker', :path => '../node_modules/@react-native-community/datetimepicker'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Add the AppsFlyer pod here
#  pod 'react-native-appsflyer', :path => '../node_modules/react-native-appsflyer'

  target 'PoppinProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  # use_flipper!()

  post_install do |installer|
    # https://stackoverflow.com/questions/73014763/react-native-ios-xcode-build-failing-for-bitcode
    # XCode build setting 에서 bitcode enabled 를 No 로 설정해도 자꾸 반영이 안 됩니다. 아래 코드를 추가해줘야 합니다.
    # #SETTING https://github.com/airbnb/lottie-ios/issues/2076#issuecomment-2019995912
    # XCode build setting 에서 other swift flag 를 '--interface'로 설정해도 자꾸 반영이 안 됩니다. 아래 코드를 추가해줘야 합니다.
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings['OTHER_SWIFT_FLAGS'] ||= ['$(inherited)', '-no-verify-emitted-module-interface']
        # 여기에 BUILD_LIBRARY_FOR_DISTRIBUTION 설정 추가
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
    ###

    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
        react_native_post_install(
          installer,
          config[:reactNativePath],
          :mac_catalyst_enabled => false,
          # :ccache_enabled => true
        )
  end
end
