/**
 * 푸시 알림 전송 사유
 * @author 도형
 */
export enum NotificationType {
  HELPFUL_REVIEW_TO_POPUP = 'HELPFUL_REVIEW_TO_POPUP',
  INTEREST_POPUP_OPEN = 'INTEREST_POPUP_OPEN',
  INTEREST_POPUP_DEADLINE = 'INTEREST_POPUP_DEADLINE',
  INTEREST_POPUP_MODIFIED = 'INTEREST_POPUP_MODIFIED',
}
